### ISSUE TITLE
Customize the Dockerfile halts the container

### ISSUE THREAD

**Issue by gmaron** [ConSol/docker-headless-vnc-container#32] opened 2017-08-30 17:58 UTC
Hi everyone,

I have this Dockerfile 

```docker
FROM consol/ubuntu-xfce-vnc:latest

MAINTAINER Gaston Maron "gastonmaron@gmail.com"
ENV REFRESHED_AT 2017-08-30

USER 0

RUN apt-get update && apt-get -y upgrade \
    && apt-get install -y build-essential \
    && apt-get install -y nano \
    && apt-get install -y net-tools \
    && apt-get install -y software-properties-common \
    && add-apt-repository -y ppa:openjdk-r/ppa \
    && apt-get update \
    && apt-get install -y openjdk-7-jdk

USER 1984

ENTRYPOINT ["/dockerstartup/vnc_startup.sh"]
```
and when I try to run the image, the container halts itself.

The log file 

```
------------------ VNC environment started ------------------

VNCSERVER started on DISPLAY= :1 
	=> connect via VNC viewer with 172.17.0.4:5901

noVNC HTML client started:
	=> connect via http://172.17.0.4:6901/?password=...

...

(xfwm4:117): libxfce4ui-WARNING **: ICE I/O Error

(xfwm4:117): libxfce4ui-WARNING **: Disconnected from session manager.

(xfsettingsd:132): libxfce4ui-WARNING **: ICE I/O Error


(xfsettingsd:132): libxfce4ui-WARNING **: Disconnected from session manager.
```

Do you know what is the problem here?

Thanks!

**Comment by toschneck** [comment] 2017-08-31 09:06
I currently tested it on my machine. And the Problem is, that you overwrite the entrypoint. If I remove the last line of your example all is working. I don't know why this is happening, but it solves the Problem :wink: @gmaron can you verfiy this?

**Comment by gmaron** [comment] 2017-08-31 14:10
Thank you so much for your help! 

It was the point. I think you should update your README to avoid this 'little' bug. 

Have a nice day!

**Comment by toschneck** [comment] 2017-08-31 18:02
@gmaron I think it's actual since a while https://github.com/ConSol/docker-headless-vnc-container#1-extend-a-image-with-your-own-software

**Comment by gmaron** [comment] 2017-08-31 18:33
Yes, the documentation is very complete and updated. But at that point, at least for me, it generated confusion. Whatever, the problem is solved.

Thanks @toschneck !

**Comment by rbo** [comment] 2017-09-01 09:49
The main problem is, if you overwrite the ```ENTRYPOINT``` it "delete" the ```CMD``` from the base image. unfortunately...

For example:
```
$ docker inspect  consol/ubuntu-xfce-vnc:latest | jq '.[] | { Entrypoint: .Config.Entrypoint, Cmd: .Config.Cmd}'
{
 "Entrypoint": [
   "/dockerstartup/vnc_startup.sh"
 ],
 "Cmd": [
   "--tail-log"
 ]
}

$ cat Dockerfile
FROM consol/ubuntu-xfce-vnc:latest
ENTRYPOINT ["/dockerstartup/vnc_startup.sh"]

$ docker build .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM consol/ubuntu-xfce-vnc:latest
---> 2af76cf39a98
Step 2 : ENTRYPOINT /dockerstartup/vnc_startup.sh
---> Using cache
---> a245e11f8d7d
Successfully built a245e11f8d7d

$ docker inspect  a245e11f8d7d | jq '.[] | { Entrypoint: .Config.Entrypoint, Cmd: .Config.Cmd}'
{
 "Entrypoint": [
   "/dockerstartup/vnc_startup.sh"
 ],
 "Cmd": null
}
```

From my opinion of view we should adjust consol/ubuntu-xfce-vnc to work with an empty ```CMD```.

**Comment by toschneck** [comment] 2017-09-01 14:00
@rbo should be fixed now,  see next docker build with tag `:dev`. Can you close the issue after reviewing?

**Comment by rbo** [comment] 2017-09-01 15:07
LGTM

**Closed by rbo** 2017-09-01 15:07 UTC
Labels: help wanted, TO REVIEW, type:refactoring
